# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04d6e9847bf9cac9f33e0555de3647d7dbda36f128dc32c5573a93663efeaa6c60a53dc395887621e206d3742451a8e7b70ace6a36ad3c38b4717553571e28a3

test:
  secret_key_base: e0676b93bd64df5d231cbbd30100a782ee477ce32a9372b9bc7f70aa235713d936198b70443a7801030b0fae916d825d22e9751499480703db18eebc8e13b107

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
